title: 'NA' #used to remove Title for simpler UI
log_level: 2
inputs:
    input0:
        source: /dev/video-usb-cam0
        format: jpeg
        width: 1280
        height: 720
        framerate: 30
    input1: 
        source: /dev/video-imx219-cam0
        subdev-id: /dev/v4l-imx219-subdev0
        width: 1640
        height: 1232
        format: rggb10
        framerate: 30
        #mirror: lr #Added option to mirror images left-right. This will increase latency!
    input2:
        source: /dev/video-imx219-cam0
        subdev-id: /dev/v4l-imx219-subdev0
        width: 1920
        height: 1080
        format: rggb
        framerate: 30

models:
    model0:
        model_path: /opt/model_zoo/TVM-OD-5120-ssdLite-mobDet-DSP-coco-320x320
        viz_threshold: 0.6
    model1:
        model_path: /opt/model_zoo/TFL-OD-2020-ssdLite-mobDet-DSP-coco-320x320
        viz_threshold: 0.6
    model2:
        model_path: /opt/model_zoo/ONR-OD-8200-yolox-nano-lite-mmdet-coco-416x416
        viz_threshold: 0.6
outputs:
    output0:
        sink: kmssink
        width: 1920 
        height: 1080
        overlay-perf-type: graph
    output1:
        sink: /opt/edgeai-test-data/output/output_video0.mkv
        width: 1920
        height: 1080
    output2:
        sink: /opt/edgeai-test-data/output/output_image_%04d.jpg
        width: 1920
        height: 1080
    output3:
        sink: remote
        width: 1920
        height: 1080
        port: 8081
        host: 127.0.0.1
        encoding: jpeg
        overlay-perf-type: graph

flows:
    flow0: [input1,model2,output0,[240,0,1440,1080]]
