
UART_MAGIC_WORD = bytearray(b'\x02\x01\x04\x03\x06\x05\x08\x07')


# Defined TLV's
MMWAVE_OUTPUT_MSG_DETECTED_POINTS                      = 1
MMWAVE_OUTPUT_MSG_RANGE_PROFILE                        = 2
MMWAVE_OUTPUT_MSG_NOISE_PROFILE                        = 3
MMWAVE_OUTPUT_MSG_AZIMUT_STATIC_HEAT_MAP               = 4
MMWAVE_OUTPUT_MSG_RANGE_DOPPLER_HEAT_MAP               = 5
MMWAVE_OUTPUT_MSG_STATS                                = 6
MMWAVE_OUTPUT_MSG_DETECTED_POINTS_SIDE_INFO            = 7
MMWAVE_OUTPUT_MSG_AZIMUT_ELEVATION_STATIC_HEAT_MAP     = 8
MMWAVE_OUTPUT_MSG_TEMPERATURE_STATS                    = 9

# IWRL6432 Out-of-box demo packets
MMWAVE_OUTPUT_EXT_MSG_DETECTED_POINTS                  = 301
MMWAVE_OUTPUT_EXT_MSG_RANGE_PROFILE_MAJOR              = 302
MMWAVE_OUTPUT_EXT_MSG_RANGE_PROFILE_MINOR              = 303
MMWAVE_OUTPUT_EXT_MSG_RANGE_AZIMUT_HEAT_MAP_MAJOR      = 304
MMWAVE_OUTPUT_EXT_MSG_RANGE_AZIMUT_HEAT_MAP_MINOR      = 305
MMWAVE_OUTPUT_MSG_EXT_STATS                            = 306
MMWAVE_OUTPUT_EXT_MSG_PRESENCE_INFO                    = 307
MMWAVE_OUTPUT_EXT_MSG_TARGET_LIST                      = 308
MMWAVE_OUTPUT_EXT_MSG_TARGET_INDEX                     = 309
MMWAVE_OUTPUT_EXT_MSG_MICRO_DOPPLER_RAW_DATA           = 310
MMWAVE_OUTPUT_EXT_MSG_MICRO_DOPPLER_FEATURES           = 311
MMWAVE_OUTPUT_EXT_MSG_RADAR_CUBE_MAJOR                 = 312
MMWAVE_OUTPUT_EXT_MSG_RADAR_CUBE_MINOR                 = 313
MMWAVE_OUTPUT_EXT_MSG_POINT_CLOUD_INDICES              = 314
MMWAVE_OUTPUT_EXT_MSG_ENHANCED_PRESENCE_INDICATION     = 315
MMWAVE_OUTPUT_EXT_MSG_ADC_SAMPLES                      = 316
MMWAVE_OUTPUT_EXT_MSG_CLASSIFIER_INFO                  = 317
MMWAVE_OUTPUT_EXT_MSG_RX_CHAN_COMPENSATION_INFO        = 318

MMWAVE_OUTPUT_MSG_GESTURE_FEATURES_6432               = 350
MMWAVE_OUTPUT_MSG_GESTURE_CLASSIFIER_6432             = 351
MMWAVE_OUTPUT_MSG_GESTURE_PRESENCE_x432               = 352
MMWAVE_OUTPUT_MSG_GESTURE_PRESENCE_THRESH_x432        = 353
MMWAVE_OUTPUT_MSG_GESTURE_CLASSIFIER_PROB_6432        = 354

MMWAVE_OUTPUT_MSG_SPHERICAL_POINTS                     = 1000
MMWAVE_OUTPUT_MSG_TRACKERPROC_3D_TARGET_LIST           = 1010
MMWAVE_OUTPUT_MSG_TRACKERPROC_TARGET_INDEX             = 1011
MMWAVE_OUTPUT_MSG_TRACKERPROC_TARGET_HEIGHT            = 1012
MMWAVE_OUTPUT_MSG_COMPRESSED_POINTS                    = 1020
MMWAVE_OUTPUT_MSG_PRESCENCE_INDICATION                 = 1021
MMWAVE_OUTPUT_MSG_OCCUPANCY_STATE_MACHINE              = 1030
MMWAVE_OUTPUT_MSG_SURFACE_CLASSIFICATION               = 1031

MMWAVE_OUTPUT_MSG_VITALSIGNS                           = 1040

MMWAVE_OUTPUT_MSG_GESTURE_FEATURES_6843                = 1050
MMWAVE_OUTPUT_MSG_GESTURE_OUTPUT_PROB_6843             = 1051

# Expected minimums and maximums to bound the range of colors used for coloring points
SNR_EXPECTED_MIN = 5
SNR_EXPECTED_MAX = 40
SNR_EXPECTED_RANGE = SNR_EXPECTED_MAX - SNR_EXPECTED_MIN
DOPPLER_EXPECTED_MIN = -30
DOPPLER_EXPECTED_MAX = 30
DOPPLER_EXPECTED_RANGE = DOPPLER_EXPECTED_MAX - DOPPLER_EXPECTED_MIN


## Application level constants
PERSISTENCE_FRAMES = 1

IMX219_DEMO_OFFSET_X = 0.000 # distance camera is to the right of radar
IMX219_DEMO_OFFSET_Y = -0.018 # distance camera is above radar
IMX219_DEMO_OFFSET_Z = 0.001 # distance camera is in front of radar
3